on:
  pull_request:
    branches:
      - develop
jobs:
  run-tests:
    name: 'Unit/Integration Tests'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run Tests
        run: mvn test
  run-build:
    name: 'Run App Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package -DskipTests
    
    
    
